version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: journal-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - journal-network

  # Backend service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: journal-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/journal?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - JWT_COOKIE_EXPIRE=30
    networks:
      - journal-network

  # Frontend service
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    container_name: journal-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - journal-network

networks:
  journal-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
